# Generated by Django 5.1.2 on 2025-08-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
    ]
